spring:
  application:
    name: security
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 1800000
      idle-timeout: 30000
      auto-commit: true
      connection-test-query: SELECT 1
  redis:
    jedis:
      pool:
        max-active: 2000
        max-idle: 500
        min-idle: 50
        max-wait: 100000ms
    timeout: 3000ms
    host: localhost
    port: 6379
    database: 0
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yibo.security.entity
logging:
  level:
    com.yibo.security.dao: debug